app.js, models/User.js, utils/auth.js
=> [전준모] ✨feat: 카카오 연동 기능 추가

controllers/planController.js, middlewares/authMiddleware.js, models/Agency.js, models/User.js
🔧 chore : 통신사, 사용자 모델 급히 수정 및 미들웨어 수정
=> 🔧 chore : 통신사, 사용자 모델 급히 수정 및 미들웨어 수정

app.js, utils/logger.js
=> [황민영]🔥 remove : 에러 메세지 중복 제거

controllers/authController.js
=> [전준모] 🎨 style: 컴포넌트 분류

controllers/planController.js, routes/planRoutes.js
[황민영] ✨ feat : 통신사별 요금제 리스트 조회
=> [황민영] ✨ feat : 통신사별 요금제 리스트 조회

app.js, controllers/adminController.js, controllers/analyticsController.js, controllers/authController.js, controllers/refreshController.js, middlewares/authMiddleware.js, models/Plans.js, models/ServiceAnalytics.js, models/Surveys.js, routes/adminRoutes.js, routes/authRoutes.js
[황민영] ✨ feat : 모델 변경 및 관리자 및 사용자 라우터 수정  🐛 fix : 충돌 및 오류 모두 수정
=> [황민영] ✨ feat : 모델 변경 및 관리자 및 사용자 라우터 수정  🐛 fix : 충돌 및 오류 모두 수정

app.js, controllers/agencyController.js, controllers/analyticsController.js, controllers/authController.js, controllers/planController.js, controllers/serviceController.js, middlewares/authMiddleware.js, middlewares/errorMiddleware.js, routes/agencyRoutes.js, routes/analyticsRoutes.js, routes/planRoutes.js, routes/serviceRoutes.js
[황민영] ✅ test : 테스트 완료, 데이터 값 필요
=> [황민영] ✅ test : 테스트 완료, 데이터 값 필요

app.js, controllers/planController.js, controllers/serviceController.js, package.json, routes/planRoutes.js, routes/serviceRoutes.js, utils/swagger.js
[황민영] 🔧 chore : 관리자도 등록할 수 있게 추가, swagger 추가
=> [황민영] 🔧 chore : 관리자도 등록할 수 있게 추가, swagger 추가

controllers/planController.js, routes/planRoutes.js, server.js
=> [황민영] ✨ feat : 요금제 조회 가능!

controllers/transactionController.js
[황민영] ✅ test : development 단계에서도 알람이 오도록 변경
=> [황민영] ✅ test : development 단계에서도 알람이 오도록 변경

controllers/userPlanController.js, routes/userPlanRoutes.js
[황민영] ✨ feat : 요금제 생성 할때 endDate도 추가, 자동 만료 구현과 내 요금제 조회, 청구서 조회 구현
=> [황민영] ✨ feat : 요금제 관련 구현

controllers/planController.js, routes/authRoutes.js
=> [황민영] 🐛 fix : 중복 제거

controllers/userPlanController.js
=> [황민영] ⚡ perf : 중복 요금제 가입 방지

middlewares/authMiddleware.js, routes/planRoutes.js
[황민영] ✨ feat : 비로그인시에도 요금제 보이도록
=> [황민영] ✨ feat : 비로그인시에도 요금제 보이도록

controllers/notificationController.js
=> [차민준] ✨ feat: 관리자 알림기능

controllers/userPlanController.js
=> [황민영] 📝 docs : const 위치 변경 

controllers/authController.js, controllers/notificationController.js
[차민준] ✨ feat: 관리자 알림 확인 기능, 삭제 기능 추가
=> [차민준] ✨ feat: 관리자 알림 확인 기능, 삭제 기능 추가

middlewares/authMiddleware.js
=> [황민영] 📝 docs : 에러메세지 변경

controllers/authController.js, package.json, scripts/seed.js, server.js, utils/scheduler.js
=> [황민영] 🔧 chore : 생일 쿠폰 자동 지급

controllers/authController.js, routes/authRoutes.js
=> [전준모] 🐛 fix : 비밀번호 변경 오류 수정

controllers/planController.js
=> [황민영] ⚡ perf : 트랜잭션 처리

controllers/transactionController.js, server.js
=> [황민영] 🔧 chore : 배포 환경 구축
